config/routes.rb
Rails.application.routes.draw do
  resources :blogs

  resources :articles

  resources :courses

  resources :projects

  resources :jobs

  resources :environments

  resources :institutions

  get 'private' => 'private#index'
  get 'about' => 'home#about'
  get 'search' => 'search#index'

  devise_for :users
  root :to => "home#index"

end

app/models/address.rb
class Address < ActiveRecord::Base
  has_many :institutions
  validates :identifier, presence: true, uniqueness: true
  validates :country, presence: true
  validates :city, presence:true
  validates :state, presence: true
end

app/models/article.rb
class Article < ActiveRecord::Base

  validates :title, presence: true
  validates :abstract, presence: true
  validates :body, presence: true
  validates :blog_id, presence: true

  validate :check_if_title_is_unique_on_blog

  def check_if_title_is_unique_on_blog
    if self.blog_id
      blog = Blog.find(self.blog_id)
      blog.articles.each do |art|
        errors.add(:title, "There is one article with that title on the blog you chose") if (art.title == self.title && art.id != self.id)
      end
    end
  end
end

app/models/blog.rb
class Blog < ActiveRecord::Base
  has_many :articles

  validates :name, presence: true
  validates :description, presence: true
  validates :user_id, presence: true
  validate :check_name_of_the_users_blog

  has_attached_file :cover, :styles => { :medium => "300x300>", :thumb => "100x100>" }, :default_url => ":style/blogs.png"
  validates_attachment_content_type :cover, :content_type => /\Aimage\/.*\Z/

  def check_name_of_the_users_blog
    if self.user_id
      user = User.find(self.user_id)
      user.blogs.each do |blog|
        errors.add(:name, "There is one blog with that name") if (blog.name == self.name && blog.id != self.id)
      end
    end
  end
end

app/models/course.rb
class Course < ActiveRecord::Base
  has_many :users
  has_many :institutions

  validates :name, presence: true
  validates :institution_id, presence: true
  validates :user_id, presence: true
end

app/models/environment.rb
class Environment < ActiveRecord::Base

  validates :name, presence: true, uniqueness: { case_sensitive: false }
end

app/models/institution.rb
class Institution < ActiveRecord::Base
  has_many :jobs
  has_many :projects
  has_many :courses
  has_attached_file :avatar, :styles => { :medium => "300x300>", :thumb => "100x100>" }, :default_url => ":style/institutions.png"
  validates_attachment_content_type :avatar, :content_type => /\Aimage\/.*\Z/

  validates :name, presence: true, uniqueness: { case_sensitive: false }
  validates :description, presence: true
  validates :acronym, presence: true, uniqueness: { case_sensitive: false }
  validates :addresses_id, presence: true

end

app/models/job.rb
class Job < ActiveRecord::Base
  has_many :users
  has_many :institutions

  validates :name, presence: true
  validates :institution_id, presence: true
  validates :user_id, presence: true
  validate :check_if_user_has_job_with_same_name
  has_attached_file :avatar, :styles => { :medium => "300x300>", :thumb => "100x100>" }, :default_url => ":style/user.png"
  validates_attachment_content_type :avatar, :content_type => /\Aimage\/.*\Z/

  def check_if_user_has_job_with_same_name
    if self.user_id
      user = User.find(self.user_id)
      user.jobs.each do |job|
        errors.add(:name, "User has a job with the same name already") if job.name == self.name
      end
    end
  end

end

app/models/project.rb
class Project < ActiveRecord::Base
  has_many :users
  has_many :institutions

  validates :name, presence: true
  validates :institution_id, presence: true
  validates :user_id, presence: true
  validate :check_if_user_has_job_with_same_name
  has_attached_file :avatar, :styles => { :medium => "300x300>", :thumb => "100x100>" }, :default_url => ":style/user.png"
  validates_attachment_content_type :avatar, :content_type => /\Aimage\/.*\Z/

  def check_if_user_has_job_with_same_name
    if self.user_id
      user = User.find(self.user_id)
      user.projects.each do |project|
        errors.add(:name, "User has a project with the same name already") if project.name == self.name
      end
    end
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :jobs
  has_many :projects
  has_many :articles
  has_many :blogs
  has_attached_file :avatar, :styles => { :medium => "300x300>", :thumb => "100x100>" }, :default_url => ":style/user.png"
  validates_attachment_content_type :avatar, :content_type => /\Aimage\/.*\Z/
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  skip_before_filter :authenticate_user!, only: [:index, :about]

  def index
  end

  def about
    @user = User.first
    @blogs = @user.blogs
  end
end

app/controllers/institutions_controller.rb
class InstitutionsController < PrivateController
  skip_before_filter :authenticate_user!, only: [:show, :index]
  before_action :set_institution, only: [:show, :edit, :update, :destroy]
  before_action :set_address, only: [:edit, :new, :create, :update]

  # GET /institutions
  # GET /institutions.json
  def index
    @institutions = Institution.all
  end

  # GET /institutions/1
  # GET /institutions/1.json
  def show
  end

  # GET /institutions/new
  def new
    @institution = Institution.new
  end

  # GET /institutions/1/edit
  def edit
  end

  # POST /institutions
  # POST /institutions.json
  def create
    @institution = Institution.new(institution_params)

    respond_to do |format|
      save_object @institution, format
    end
  end

  # PATCH/PUT /institutions/1
  # PATCH/PUT /institutions/1.json
  def update
    respond_to do |format|
      update_params @institution, institution_params, format
    end
  end

  # DELETE /institutions/1
  # DELETE /institutions/1.json
  def destroy
    destroy_object @institution
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_institution
      @institution = Institution.find(params[:id])
    end

    def set_address
      @addresses = []
      Address.all.each{|address| @addresses << [address.identifier, address.id]}
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def institution_params
      params.require(:institution).permit(:name, :description, :avatar, :acronym, :addresses_id)
    end
end

app/controllers/jobs_controller.rb
class JobsController < PrivateController
  skip_before_filter :authenticate_user!, only: [:show, :index]
  before_action :set_job, only: [:show, :edit, :update, :destroy]
  before_action :set_institution, only: [:edit, :new, :create, :update]

  # GET /jobs
  # GET /jobs.json
  def index
    @jobs = Job.all
  end

  # GET /jobs/1
  # GET /jobs/1.json
  def show
  end

  # GET /jobs/new
  def new
    @job = Job.new

  end

  # GET /jobs/1/edit
  def edit
  end

  # POST /jobs
  # POST /jobs.json
  def create
    @job = Job.new(job_params)
    add_inst_and_user @job, job_params

    respond_to do |format|
      save_object @job, format
    end
  end

  # PATCH/PUT /jobs/1
  # PATCH/PUT /jobs/1.json
  def update
    respond_to do |format|
      update_params @job, job_params, format
    end
  end

  # DELETE /jobs/1
  # DELETE /jobs/1.json
  def destroy
    destroy_object @job
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_job
      @job = Job.find(params[:id])
    end

    def set_institution
      @institutions = []
      Institution.all.each {|inst| @institutions << [inst.acronym, inst.id]}
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def job_params
      params.require(:job).permit(:name, :institution_id, :responsabilities, :position, :start_date, :current, :end_date, :link, :avatar)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/blogs_helper.rb
module BlogsHelper
end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/helpers/environments_helper.rb
module EnvironmentsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/institutions_helper.rb
module InstitutionsHelper
end

app/helpers/jobs_helper.rb
module JobsHelper
end

app/helpers/private_helper.rb
module PrivateHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/search_helper.rb
module SearchHelper
end

app/views/institutions/_form.html.erb
<%= form_for(@institution) do |f| %>
  <% if @institution.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@institution.errors.count, "error") %> prohibited this institution from being saved:</h2>

      <ul>
      <% @institution.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label t(:name) %><br />
    <%= f.text_field :name, autofocus: true, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label t(:acronym) %><br />
    <%= f.text_field :acronym, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label t(:address) %><br />
    <%= f.select(:addresses_id, options_for_select(@addresses, @institution.addresses_id), {}, {class: "form-control"}) %>
  </div>

  <div class="form-group">
    <%= f.label t(:description) %><br />
    <%= f.text_area :description, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label t(:avatar) %> <br />
    <%= f.file_field :avatar, class: "form-control" %>
  </div>

  <div class="actions">
    <%= f.submit class: "btn btn-default" %>
  </div>
<% end %>

app/views/institutions/_show_logged_in.html.erb
<h1 class="text-center"><%=t "Institutions" %></h1>
<div class="table-responsive">
  <table class="table table-striped table-hover">
    <thead>
      <tr>
        <th colspan="1" class="text-center"><%=t "Name" %></th>
        <th colspan="3" class="text-center"><%=t "Actions" %></th>
      </tr>
    </thead>

    <tbody>
      <% @institutions.each do |institution| %>
      <tr>
        <td  width="75%"><%= "#{institution.name}" %>
          <td><%= link_to institution, class: "btn btn-default" do %>
            <i class="glyphicon glyphicon-home", aria-hidden="true"></i></td>
          <% end %>
          <td><%= link_to edit_institution_path(institution), class: "btn btn-default" do %>
            <i class="glyphicon glyphicon-pencil" aria-hidden="true"></i></td>
          <% end %>
          <td><%= link_to institution, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-default" do %>
            <i class="glyphicon glyphicon-trash" aria-hidden="true"></i></td>
          <% end %>
        </tr>
        <% end %>
      </tbody>
  </table>
</div>

  <br>

  <%= link_to t('New institution'), new_institution_path, class: "btn btn-default" %>

app/views/institutions/_show_not_logged_in.html.erb
<% @institutions.each_with_index do |institution, index| %>
  <div class="row institutions">
    <% if (index % 2 == 0) %>
        <div class="text col-xs-12 col-sm-6 col-md-8 pull-rigth description-institutions">
            <h3 class="name-description"><%= link_to institution.name, institution, class: "links-buttons" %></h3>
            <div class="image img-responsive visible-xs pull-left image-institutions">
              <%= image_tag institution.avatar.url(:thumb) %>
            </div>
            <div class="text-justify"><%= institution.description %></div>
        </div>
        <div class="image img-responsive hidden-xs col-sm-4 col-md-4 pull-left image-institutions">
          <%= image_tag institution.avatar.url(:medium) %>
        </div>
    <% else %>
        <div class="image img-responsive hidden-xs col-sm-4 col-md-4 pull-rigth image-institutions">
          <%= image_tag institution.avatar.url(:medium) %>
        </div>
        <div class="text  col-xs-12 col-sm-6 col-md-8 pull-left description-institutions">
          <h3 class="name-description"><%= link_to institution.name, institution, class: "links-buttons" %></h3>
          <div class="image img-responsive visible-xs pull-right image-institutions">
            <%= image_tag institution.avatar.url(:thumb) %>
          </div>
          <div class="text-justify"><%= institution.description %></div>
        </div>
    <% end %>
  </div>
<% end %>

app/views/institutions/edit.html.erb
<div class="col-xs-12 col-sm-6 col-md-2 hidden-sm ">
</div>

<div class="col-xs-12 col-sm-12 col-md-6">

  <div class="text-center">
    <h1><%=t "Editing Institution" %></h1>
  </div>

    <%= render 'form' %>

    <%= link_to t('Show'), @institution, class: "btn btn-default" %>
    <%= link_to t('Back'), institutions_path, class: "btn btn-default" %>
</div>

app/views/institutions/index.html.erb
<% if user_signed_in? %>

  <%= render 'institutions/show_logged_in' %>

<% else %>

  <%= render 'institutions/show_not_logged_in' %>

<% end %>

app/views/institutions/new.html.erb
<div class="col-xs-12 col-sm-6 col-md-2 hidden-sm ">
</div>

<div class="col-xs-12 col-sm-12 col-md-6">

  <div class="text-center">
    <h1><%=t "New Institution" %></h1>
  </div>

  <%= render 'form' %>

  <%= link_to t('Back'), institutions_path, class: "btn btn-default" %>
</div>

app/views/institutions/show.html.erb
<div class="row">
  <div class="pull-left" style="margin-left: 40px"> <%= image_tag @institution.avatar.url(:thumb) %></div>
  <div class="pull-right" style="display: inline-block; margin-right: 30px; vertical-alignment: middle;"> <h4><%= @institution.name %></h4></div>
</div>

<div class="row">

  <div class="text-justify" style="margin-left: 30px; margin-right: 30px; margin-top: 20px;"> <%= @institution.description %> </div>

</div>

<br />

<% if user_signed_in? %>
  <%= link_to t('Edit'), edit_institution_path(@institution), class: "btn btn-default" %>
  <%= link_to t('Back'), institutions_path, class: "btn btn-default" %>
<% end %>