config/routes.rb
Rails.application.routes.draw do
  resources :blogs

  resources :articles

  resources :courses

  resources :projects

  resources :jobs

  resources :environments

  resources :institutions

  get 'private' => 'private#index'
  get 'about' => 'home#about'
  get 'search' => 'search#index'

  devise_for :users
  root :to => "home#index"

end

app/models/address.rb
class Address < ActiveRecord::Base
  has_many :institutions
  validates :identifier, presence: true, uniqueness: true
  validates :country, presence: true
  validates :city, presence:true
  validates :state, presence: true
end

app/models/article.rb
class Article < ActiveRecord::Base

  validates :title, presence: true
  validates :abstract, presence: true
  validates :body, presence: true
  validates :blog_id, presence: true

  validate :check_if_title_is_unique_on_blog

  def check_if_title_is_unique_on_blog
    if self.blog_id
      blog = Blog.find(self.blog_id)
      blog.articles.each do |art|
        errors.add(:title, "There is one article with that title on the blog you chose") if (art.title == self.title && art.id != self.id)
      end
    end
  end
end

app/models/blog.rb
class Blog < ActiveRecord::Base
  has_many :articles

  validates :name, presence: true
  validates :description, presence: true
  validates :user_id, presence: true
  validate :check_name_of_the_users_blog

  has_attached_file :cover, :styles => { :medium => "300x300>", :thumb => "100x100>" }, :default_url => ":style/blogs.png"
  validates_attachment_content_type :cover, :content_type => /\Aimage\/.*\Z/

  def check_name_of_the_users_blog
    if self.user_id
      user = User.find(self.user_id)
      user.blogs.each do |blog|
        errors.add(:name, "There is one blog with that name") if (blog.name == self.name && blog.id != self.id)
      end
    end
  end
end

app/models/course.rb
class Course < ActiveRecord::Base
  has_many :users
  has_many :institutions

  validates :name, presence: true
  validates :institution_id, presence: true
  validates :user_id, presence: true
end

app/models/environment.rb
class Environment < ActiveRecord::Base

  validates :name, presence: true, uniqueness: { case_sensitive: false }
end

app/models/institution.rb
class Institution < ActiveRecord::Base
  has_many :jobs
  has_many :projects
  has_many :courses
  has_attached_file :avatar, :styles => { :medium => "300x300>", :thumb => "100x100>" }, :default_url => ":style/institutions.png"
  validates_attachment_content_type :avatar, :content_type => /\Aimage\/.*\Z/

  validates :name, presence: true, uniqueness: { case_sensitive: false }
  validates :description, presence: true
  validates :acronym, presence: true, uniqueness: { case_sensitive: false }
  validates :addresses_id, presence: true

end

app/models/job.rb
class Job < ActiveRecord::Base
  has_many :users
  has_many :institutions

  validates :name, presence: true
  validates :institution_id, presence: true
  validates :user_id, presence: true
  validate :check_if_user_has_job_with_same_name
  has_attached_file :avatar, :styles => { :medium => "300x300>", :thumb => "100x100>" }, :default_url => ":style/user.png"
  validates_attachment_content_type :avatar, :content_type => /\Aimage\/.*\Z/

  def check_if_user_has_job_with_same_name
    if self.user_id
      user = User.find(self.user_id)
      user.jobs.each do |job|
        errors.add(:name, "User has a job with the same name already") if job.name == self.name
      end
    end
  end

end

app/models/project.rb
class Project < ActiveRecord::Base
  has_many :users
  has_many :institutions

  validates :name, presence: true
  validates :institution_id, presence: true
  validates :user_id, presence: true
  validate :check_if_user_has_job_with_same_name
  has_attached_file :avatar, :styles => { :medium => "300x300>", :thumb => "100x100>" }, :default_url => ":style/user.png"
  validates_attachment_content_type :avatar, :content_type => /\Aimage\/.*\Z/

  def check_if_user_has_job_with_same_name
    if self.user_id
      user = User.find(self.user_id)
      user.projects.each do |project|
        errors.add(:name, "User has a project with the same name already") if project.name == self.name
      end
    end
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :jobs
  has_many :projects
  has_many :articles
  has_many :blogs
  has_attached_file :avatar, :styles => { :medium => "300x300>", :thumb => "100x100>" }, :default_url => ":style/user.png"
  validates_attachment_content_type :avatar, :content_type => /\Aimage\/.*\Z/
end

app/controllers/articles_controller.rb
class ArticlesController < PrivateController
  before_action :set_article, only: [:show, :edit, :update, :destroy]
  before_action :set_blogs, only: [:new, :edit, :create, :update]
  skip_before_filter :authenticate_user!, only: [:show, :index]
  before_filter :is_logged_in?, only: [:edit, :update, :destroy, :new, :create]

  # GET /articles
  # GET /articles.json
  def index
    @articles = Article.all
    @blogs = User.first.blogs
  end

  # GET /articles/1
  # GET /articles/1.json
  def show
  end

  # GET /articles/new
  def new
    @article = Article.new
  end

  # GET /articles/1/edit
  def edit
  end

  # POST /articles
  # POST /articles.json
  def create
    @article = Article.new(article_params)
    respond_to do |format|
      save_object @article, format
    end
  end

  # PATCH/PUT /articles/1
  # PATCH/PUT /articles/1.json
  def update
    respond_to do |format|
      update_params @article, article_params, format
    end
  end

  # DELETE /articles/1
  # DELETE /articles/1.json
  def destroy
    destroy_object @article
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_article
      @article = Article.find(params[:id])
    end

    def set_blogs
      @blogs = []
      current_user.blogs.each {|blog| @blogs << [blog.name, blog.id]}
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def article_params
      params.require(:article).permit(:title, :abstract, :body, :accept_comments, :published, :blog_id)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  skip_before_filter :authenticate_user!, only: [:index, :about]

  def index
  end

  def about
    @user = User.first
    @blogs = @user.blogs
  end
end

app/controllers/jobs_controller.rb
class JobsController < PrivateController
  skip_before_filter :authenticate_user!, only: [:show, :index]
  before_action :set_job, only: [:show, :edit, :update, :destroy]
  before_action :set_institution, only: [:edit, :new, :create, :update]

  # GET /jobs
  # GET /jobs.json
  def index
    @jobs = Job.all
  end

  # GET /jobs/1
  # GET /jobs/1.json
  def show
  end

  # GET /jobs/new
  def new
    @job = Job.new

  end

  # GET /jobs/1/edit
  def edit
  end

  # POST /jobs
  # POST /jobs.json
  def create
    @job = Job.new(job_params)
    add_inst_and_user @job, job_params

    respond_to do |format|
      save_object @job, format
    end
  end

  # PATCH/PUT /jobs/1
  # PATCH/PUT /jobs/1.json
  def update
    respond_to do |format|
      update_params @job, job_params, format
    end
  end

  # DELETE /jobs/1
  # DELETE /jobs/1.json
  def destroy
    destroy_object @job
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_job
      @job = Job.find(params[:id])
    end

    def set_institution
      @institutions = []
      Institution.all.each {|inst| @institutions << [inst.acronym, inst.id]}
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def job_params
      params.require(:job).permit(:name, :institution_id, :responsabilities, :position, :start_date, :current, :end_date, :link, :avatar)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/blogs_helper.rb
module BlogsHelper
end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/helpers/environments_helper.rb
module EnvironmentsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/institutions_helper.rb
module InstitutionsHelper
end

app/helpers/jobs_helper.rb
module JobsHelper
end

app/helpers/private_helper.rb
module PrivateHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/search_helper.rb
module SearchHelper
end

app/views/articles/_form.html.erb
<%= form_for(@article) do |f| %>
  <% if @article.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@article.errors.count, "error") %> prohibited this article from being saved:</h2>

      <ul>
      <% @article.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label t(:title) %><br />
    <%= f.text_field :title, autofocus: true, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label t(:abstract) %> <br />
    <%= f.text_area :abstract, class: "form-control"  %>
  </div>
  <%= tinymce %>
  <div class="form-group">
    <%= f.label t(:body) %> <br />
    <%= f.text_area :body, class: "form-control tinymce", rows: 40  %>
  </div>

  <div class="form-group">
    <%= f.label t(:blog) %> <br />
    <%= f.select(:blog_id, options_for_select(@blogs, @article.blog_id),{}, {class: "form-control"}) %>
  </div>

  <div class="form-group checkbox">
    <%= f.label t(:published) do %> <br />
    <%= f.check_box :published %>
    <%= t("Want to publish it now?") %>
    <% end %>
  </div>

  <div class="form-group checkbox">
    <%= f.label t(:accept_comments) do %> <br />
    <%= f.check_box :accept_comments %>
    <%= t("Want to accept comments for this?") %>
    <% end %>
  </div>

  <div class="actions">
    <%= f.submit class: 'btn btn-default'  %>
  </div>
<% end %>

app/views/articles/_show_logged_in.erb
<h1 class="text-center"><%=t "Articles" %></h1>
<div class="table-responsive">
  <table class="table table-striped table-hover">
    <thead>
      <tr>
        <th colspan="1" class="text-center"><%=t "Name" %></th>
        <th colspan="3" class="text-center"><%=t "Actions" %></th>
      </tr>
    </thead>

    <tbody>
      <% @articles.each do |article| %>
        <tr>
          <td width="75%"><%= "#{article.title}" %>
          <td>
            <%= link_to article, class: "btn btn-default" do %>
              <i class="glyphicon glyphicon-home", aria-hidden="true"></i></td>
            <% end %>
          <td>
            <%= link_to edit_article_path(article), class: "btn btn-default" do %>
              <i class="glyphicon glyphicon-pencil" aria-hidden="true"></i></td>
              <% end %>
          <td>
            <%= link_to article, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-default" do %>
              <i class="glyphicon glyphicon-trash" aria-hidden="true"></i></td>
              <% end %>
          </tr>
        <% end %>
      </tbody>
  </table>
</div>

<br>

<%= link_to t('New article'), new_article_path, class: "btn btn-default" %>

app/views/articles/_show_not_logged_in.erb
<ul id="myTab" class="nav nav-tabs" role="tablist">
  <% @blogs.each_with_index do |blog, index| %>
    <% if index == 0 %>
      <li role="presentation" id="<%= blog.name.downcase.tr(' ', '_') %>" class="active"><%= link_to blog.name, "#" %> </li>
    <% else %>
      <li role="presentation" id="<%= blog.name.downcase.tr(' ', '_') %>"><%= link_to blog.name, "#" %> </li>
    <% end %>
  <% end %>
</ul>

<% @articles.each do |article| %>
  <% blog_name = Blog.find(article.blog_id).name %>
  <div id="myTabContent <%= blog_name.downcase.tr(' ', '_')%>_id" class="tab-content">
    <div role="tabpanel" class="tab-pane fade <%= blog_name.downcase.tr(' ', '_')%>_panel" aria-labelledby="<%= blog_name.downcase.tr(' ', '-') %>">
      <h3><%= link_to article.title, article, class: "link-buttons"  %></h3>
      <h4><%= link_to article.abstract.truncate_words(20), article, class: "link-buttons"  %></h4>
    </div>
  </div>
<% end %>

<script>
  $('#myTab a').click(function (e) {
    e.preventDefault()
    $('.active').removeClass('active');
    var tab = $(this).parent().attr('id');
    $('#'+tab).addClass('active');
    $('.tab-pane').each(function(){
      $(this).removeClass('in active');
    })
    var tab_to_show = tab + '_panel';
    $('.'+tab_to_show).each(function(){
      $(this).addClass('in active');
    });
  })

  $( document ).ready(function() {
    // Handler for .ready() called.
    var id = $('.active').attr('id') + '_panel';
    $('.'+id).addClass('in active');
  });
</script>

app/views/articles/edit.html.erb
<div class="col-xs-12 col-sm-12 col-md-12">

  <div class="text-center">
    <h1><%=t "Edit Article" %></h1>
  </div>
    <%= render 'form' %>

    <%= link_to t('Show'), @article, class: "btn btn-default" %>
    <%= link_to t('Back'), articles_path, class: "btn btn-default" %>
</div>

app/views/articles/index.html.erb
<% if user_signed_in? %>

<%= render 'articles/show_logged_in' %>

<% else %>

<%= render 'articles/show_not_logged_in' %>

<% end %>

app/views/articles/new.html.erb
<div class="col-xs-12 col-sm-12 col-md-12">

  <div class="text-center">
    <h1><%=t "New Article" %></h1>
  </div>

  <%= render 'form' %>

  <%= link_to t('Back'), articles_path, class: "btn btn-default" %>
</div>

app/views/articles/show.html.erb
<h1 class="text-center"> <%= @article.title %> </h1>
<br />
<small class="pull-center"> <%= @article.abstract %> </small>
<br />
<br />
<p> <%= @article.body.html_safe %> </p>


<% if user_signed_in? %>
  <%= link_to t('Edit'), edit_article_path(@article), class:'btn btn-default' %>
  <%= link_to t('Back'), articles_path, class:'btn btn-default' %>
<% end %>