config/routes.rb
Rails.application.routes.draw do
  resources :blogs

  resources :articles

  resources :courses

  resources :projects

  resources :jobs

  resources :environments

  resources :institutions

  get 'private' => 'private#index'
  get 'about' => 'home#about'
  get 'search' => 'search#index'

  devise_for :users
  root :to => "home#index"

end

app/models/address.rb
class Address < ActiveRecord::Base
  has_many :institutions
  validates :identifier, presence: true, uniqueness: true
  validates :country, presence: true
  validates :city, presence:true
  validates :state, presence: true
end

app/models/article.rb
class Article < ActiveRecord::Base

  validates :title, presence: true
  validates :abstract, presence: true
  validates :body, presence: true
  validates :blog_id, presence: true

  validate :check_if_title_is_unique_on_blog

  def check_if_title_is_unique_on_blog
    if self.blog_id
      blog = Blog.find(self.blog_id)
      blog.articles.each do |art|
        errors.add(:title, "There is one article with that title on the blog you chose") if (art.title == self.title && art.id != self.id)
      end
    end
  end
end

app/models/blog.rb
class Blog < ActiveRecord::Base
  has_many :articles

  validates :name, presence: true
  validates :description, presence: true
  validates :user_id, presence: true
  validate :check_name_of_the_users_blog

  has_attached_file :cover, :styles => { :medium => "300x300>", :thumb => "100x100>" }, :default_url => ":style/blogs.png"
  validates_attachment_content_type :cover, :content_type => /\Aimage\/.*\Z/

  def check_name_of_the_users_blog
    if self.user_id
      user = User.find(self.user_id)
      user.blogs.each do |blog|
        errors.add(:name, "There is one blog with that name") if (blog.name == self.name && blog.id != self.id)
      end
    end
  end
end

app/models/course.rb
class Course < ActiveRecord::Base
  has_many :users
  has_many :institutions

  validates :name, presence: true
  validates :institution_id, presence: true
  validates :user_id, presence: true
end

app/models/environment.rb
class Environment < ActiveRecord::Base

  validates :name, presence: true, uniqueness: { case_sensitive: false }
end

app/models/institution.rb
class Institution < ActiveRecord::Base
  has_many :jobs
  has_many :projects
  has_many :courses
  has_attached_file :avatar, :styles => { :medium => "300x300>", :thumb => "100x100>" }, :default_url => ":style/institutions.png"
  validates_attachment_content_type :avatar, :content_type => /\Aimage\/.*\Z/

  validates :name, presence: true, uniqueness: { case_sensitive: false }
  validates :description, presence: true
  validates :acronym, presence: true, uniqueness: { case_sensitive: false }
  validates :addresses_id, presence: true

end

app/models/job.rb
class Job < ActiveRecord::Base
  has_many :users
  has_many :institutions

  validates :name, presence: true
  validates :institution_id, presence: true
  validates :user_id, presence: true
  validate :check_if_user_has_job_with_same_name
  has_attached_file :avatar, :styles => { :medium => "300x300>", :thumb => "100x100>" }, :default_url => ":style/user.png"
  validates_attachment_content_type :avatar, :content_type => /\Aimage\/.*\Z/

  def check_if_user_has_job_with_same_name
    if self.user_id
      user = User.find(self.user_id)
      user.jobs.each do |job|
        errors.add(:name, "User has a job with the same name already") if job.name == self.name
      end
    end
  end

end

app/models/project.rb
class Project < ActiveRecord::Base
  has_many :users
  has_many :institutions

  validates :name, presence: true
  validates :institution_id, presence: true
  validates :user_id, presence: true
  validate :check_if_user_has_job_with_same_name
  has_attached_file :avatar, :styles => { :medium => "300x300>", :thumb => "100x100>" }, :default_url => ":style/user.png"
  validates_attachment_content_type :avatar, :content_type => /\Aimage\/.*\Z/

  def check_if_user_has_job_with_same_name
    if self.user_id
      user = User.find(self.user_id)
      user.projects.each do |project|
        errors.add(:name, "User has a project with the same name already") if project.name == self.name
      end
    end
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :jobs
  has_many :projects
  has_many :articles
  has_many :blogs
  has_attached_file :avatar, :styles => { :medium => "300x300>", :thumb => "100x100>" }, :default_url => ":style/user.png"
  validates_attachment_content_type :avatar, :content_type => /\Aimage\/.*\Z/
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  skip_before_filter :authenticate_user!, only: [:index, :about]

  def index
  end

  def about
    @user = User.first
    @blogs = @user.blogs
  end
end

app/controllers/jobs_controller.rb
class JobsController < PrivateController
  skip_before_filter :authenticate_user!, only: [:show, :index]
  before_action :set_job, only: [:show, :edit, :update, :destroy]
  before_action :set_institution, only: [:edit, :new, :create, :update]

  # GET /jobs
  # GET /jobs.json
  def index
    @jobs = Job.all
  end

  # GET /jobs/1
  # GET /jobs/1.json
  def show
  end

  # GET /jobs/new
  def new
    @job = Job.new

  end

  # GET /jobs/1/edit
  def edit
  end

  # POST /jobs
  # POST /jobs.json
  def create
    @job = Job.new(job_params)
    add_inst_and_user @job, job_params

    respond_to do |format|
      save_object @job, format
    end
  end

  # PATCH/PUT /jobs/1
  # PATCH/PUT /jobs/1.json
  def update
    respond_to do |format|
      update_params @job, job_params, format
    end
  end

  # DELETE /jobs/1
  # DELETE /jobs/1.json
  def destroy
    destroy_object @job
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_job
      @job = Job.find(params[:id])
    end

    def set_institution
      @institutions = []
      Institution.all.each {|inst| @institutions << [inst.acronym, inst.id]}
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def job_params
      params.require(:job).permit(:name, :institution_id, :responsabilities, :position, :start_date, :current, :end_date, :link, :avatar)
    end
end

app/controllers/projects_controller.rb
class ProjectsController < PrivateController
  skip_before_filter :authenticate_user!, only: [:show, :index]
  before_action :set_project, only: [:show, :edit, :update, :destroy]
  before_action :set_institution, only: [:edit, :new, :create, :update]

  # GET /projects
  # GET /projects.json
  def index
    @projects = Project.all
  end

  # GET /projects/1
  # GET /projects/1.json
  def show
  end

  # GET /projects/new
  def new
    @project = Project.new
  end

  # GET /projects/1/edit
  def edit
  end

  # POST /projects
  # POST /projects.json
  def create
    @project = Project.new(project_params)
    add_inst_and_user @project, project_params

    respond_to do |format|
      save_object @project, format
    end
  end

  # PATCH/PUT /projects/1
  # PATCH/PUT /projects/1.json
  def update
    respond_to do |format|
      update_params @project, project_params, format
    end
  end

  # DELETE /projects/1
  # DELETE /projects/1.json
  def destroy
    destroy_object @project
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_project
      @project = Project.find(params[:id])
    end

    def set_institution
      @institutions = []
      Institution.all.each {|inst| @institutions << [inst.acronym, inst.id]}
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def project_params
      params.require(:project).permit(:name, :institution_id, :responsabilities, :position, :start_date, :current, :end_date, :avatar)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/blogs_helper.rb
module BlogsHelper
end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/helpers/environments_helper.rb
module EnvironmentsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/institutions_helper.rb
module InstitutionsHelper
end

app/helpers/jobs_helper.rb
module JobsHelper
end

app/helpers/private_helper.rb
module PrivateHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/search_helper.rb
module SearchHelper
end

app/views/projects/_form.html.erb
<%= form_for(@project) do |f| %>
  <% if @project.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@project.errors.count, "error") %> prohibited this project from being saved:</h2>

      <ul>
      <% @project.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label t(:name) %><br />
    <%= f.text_field :name, autofocus: true, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label t(:institutions) %><br />
    <%= f.select(:institution_id, options_for_select(@institutions, @project.institution_id),{}, {class: "form-control"}) %>
  </div>

  <div class="form-group">
    <%= f.label t(:responsabilities) %> <br />
    <%= f.text_field :responsabilities, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label t(:position) %> <br />
    <%= f.text_field :position, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label t(:start_date) %><br />
    <%= f.date_field :start_date %>
  </div>

  <div class="form-group">
    <%= f.label t(:avatar) %><br />
    <%= f.file_field :avatar, class: "form-control" %>
  </div>

  <div class="checkbox form-group">
    <%= f.label :current do %>
    <%= f.check_box :current %>
    <%=t "Current Project" %>
    <% end %>
  </div>

  <div class=""form-group"">
    <%= f.label t(:end_date) %><br />
    <%= f.date_field :end_date, class: "form-control" %>
  </div>

  <div class="actions">
    <%= f.submit class: "btn btn-default" %>
  </div>
<% end %>

app/views/projects/_show_logged_in.html.erb
<h1 class="text-center"><%=t "Projects" %></h1>
<div class="table-responsive">
  <table class="table table-striped table-hover">
    <thead>
      <tr>
        <th colspan="1" class="text-center"><%=t "Name" %></th>
        <th colspan="3" class="text-center"><%=t "Actions" %></th>
      </tr>
    </thead>

    <tbody>
      <% @projects.each do |project| %>
        <tr>
          <td  width="75%"><%= "#{project.name}" %>
          <td colspan="3"><%= link_to project, class: "btn btn-default" do %>
            <i class="glyphicon glyphicon-home", aria-hidden="true"></i>
          <% end %>
          <td><%= link_to edit_project_path(project), class: "btn btn-default" do %>
            <i class="glyphicon glyphicon-pencil" aria-hidden="true"></i>
          <% end %>
          <td><%= link_to project, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-default" do %>
            <i class="glyphicon glyphicon-trash" aria-hidden="true"></i></td>
          <% end %>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

<br>

<%= link_to t('New Project'), new_project_path, class: "btn btn-default" %>

app/views/projects/_show_not_logged_in.html.erb
<% @projects.each_with_index do |project, index| %>
<div class="row institutions">
  <% if (index % 2 == 0) %>
  <div class="text col-xs-12 col-sm-6 col-md-8 pull-rigth description-institutions">
    <h3 class="name-description"><%= link_to project.name, project, class: "links-buttons" %></h3>
    <div class="image img-responsive visible-xs pull-left image-institutions">
      <%= image_tag project.avatar.url(:thumb) %>
    </div>
    <div class="text-justify pull-right">
      <h5><%=t "Responsabilities: #{project.responsabilities}" unless project.responsabilities.nil? %></h5>
      <h5><%=t "Position: #{project.position}" unless project.position.nil? %></h5>
      <% current = project.current ? "Yes" : "No" %>
      <h5><%=t "Current: #{current}" %></h5>
      <h5><%=t "Start date: #{project.start_date.strftime('%d/%m/%Y')}" unless project.start_date.nil? %></h5>
      <h5><%=t "End date: #{project.end_date.strftime('%d/%m/%Y')}" unless project.end_date.nil?%></h5>
      <h5><%=t "Institution: #{Institution.find(project.institution_id).name}"%></h5>
    </div>
  </div>
  <div class="image img-responsive hidden-xs col-sm-6 col-md-4 pull-left image-institutions">
    <%= image_tag project.avatar.url(:medium) %>
  </div>
  <% else %>
  <div class="text  col-xs-6 col-sm-6 col-md-8 pull-left description-institutions">
    <h3 class="name-description"><%= link_to project.name, project, class: "links-buttons" %></h3>
    <div class="image img-responsive visible-xs pull-left image-institutions">
      <%= image_tag project.avatar.url(:thumb) %>
    </div>
    <div class="text-justify pull-right">
      <h5><%=t "Responsabilities: #{project.responsabilities}" unless project.responsabilities.nil? %></h5>
      <h5><%=t "Position: #{project.position}" unless project.position.nil? %></h5>
      <% current = project.current ? "Yes" : "No" %>
      <h5><%=t "Current: #{current}" %></h5>
      <h5><%=t "Start date: #{project.start_date.strftime('%d/%m/%Y')}" unless project.start_date.nil? %></h5>
      <h5><%=t "End date: #{project.end_date.strftime('%d/%m/%Y')}" unless project.end_date.nil?%></h5>
      <h5><%=t "Institution: #{Institution.find(project.institution_id).name}"%></h5>
    </div>
  </div>
  <div class="image img-responsive hidden-xs col-sm-6 col-md-4 pull-left image-institutions">
    <%= image_tag project.avatar.url(:medium) %>
  </div>
  <% end %>
</div>
<div class="post"></div>
<% end %>

app/views/projects/edit.html.erb
<div class="col-xs-12 col-sm-6 col-md-2 hidden-sm ">
</div>

<div class="col-xs-12 col-sm-12 col-md-6">

  <div class="text-center">
    <h1><%=t "Editing Project" %></h1>
  </div>

  <%= render 'form' %>

  <%= link_to t('Show'), @project, class: "btn btn-default" %>
  <%= link_to t('Back'), projects_path, class: "btn btn-default" %>
</div>

app/views/projects/index.html.erb
<% if user_signed_in? %>

  <%= render 'projects/show_logged_in' %>

<% else %>

  <%= render 'projects/show_not_logged_in' %>

<% end %>

app/views/projects/new.html.erb
<div class="col-xs-12 col-sm-6 col-md-2 hidden-sm ">
</div>

<div class="col-xs-12 col-sm-12 col-md-6">

  <div class="text-center">
    <h1><%=t "New Project" %></h1>
  </div>

  <%= render 'form' %>

  <%= link_to t('Back'), projects_path, class: "btn btn-default" %>
</div>

app/views/projects/show.html.erb
<div class="row">
  <div class="pull-left" style="margin-left: 40px"> <%= image_tag @project.avatar.url(:thumb) %></div>
  <div class="pull-right" style="display: inline-block; margin-right: 30px; vertical-alignment: middle;"> <h4><%= @project.name %></h4></div>
</div>

<div class="row">

  <div class="text-justify" style="margin-left: 30px; margin-right: 30px; margin-top: 20px;"> <%= @project.responsabilities %> </div>

</div>

<% if user_signed_in? %>
  <%= link_to t('Edit'), edit_project_path(@project) %> |
  <%= link_to t('Back'), projects_path %>
<% end %>