config/routes.rb
Rails.application.routes.draw do
  resources :blogs

  resources :articles

  resources :courses

  resources :projects

  resources :jobs

  resources :environments

  resources :institutions

  get 'private' => 'private#index'
  get 'about' => 'home#about'
  get 'search' => 'search#index'

  devise_for :users
  root :to => "home#index"

end

app/models/address.rb
class Address < ActiveRecord::Base
  has_many :institutions
  validates :identifier, presence: true, uniqueness: true
  validates :country, presence: true
  validates :city, presence:true
  validates :state, presence: true
end

app/models/article.rb
class Article < ActiveRecord::Base

  validates :title, presence: true
  validates :abstract, presence: true
  validates :body, presence: true
  validates :blog_id, presence: true

  validate :check_if_title_is_unique_on_blog

  def check_if_title_is_unique_on_blog
    if self.blog_id
      blog = Blog.find(self.blog_id)
      blog.articles.each do |art|
        errors.add(:title, "There is one article with that title on the blog you chose") if (art.title == self.title && art.id != self.id)
      end
    end
  end
end

app/models/blog.rb
class Blog < ActiveRecord::Base
  has_many :articles

  validates :name, presence: true
  validates :description, presence: true
  validates :user_id, presence: true
  validate :check_name_of_the_users_blog

  has_attached_file :cover, :styles => { :medium => "300x300>", :thumb => "100x100>" }, :default_url => ":style/blogs.png"
  validates_attachment_content_type :cover, :content_type => /\Aimage\/.*\Z/

  def check_name_of_the_users_blog
    if self.user_id
      user = User.find(self.user_id)
      user.blogs.each do |blog|
        errors.add(:name, "There is one blog with that name") if (blog.name == self.name && blog.id != self.id)
      end
    end
  end
end

app/models/course.rb
class Course < ActiveRecord::Base
  has_many :users
  has_many :institutions

  validates :name, presence: true
  validates :institution_id, presence: true
  validates :user_id, presence: true
end

app/models/environment.rb
class Environment < ActiveRecord::Base

  validates :name, presence: true, uniqueness: { case_sensitive: false }
end

app/models/institution.rb
class Institution < ActiveRecord::Base
  has_many :jobs
  has_many :projects
  has_many :courses
  has_attached_file :avatar, :styles => { :medium => "300x300>", :thumb => "100x100>" }, :default_url => ":style/institutions.png"
  validates_attachment_content_type :avatar, :content_type => /\Aimage\/.*\Z/

  validates :name, presence: true, uniqueness: { case_sensitive: false }
  validates :description, presence: true
  validates :acronym, presence: true, uniqueness: { case_sensitive: false }
  validates :addresses_id, presence: true

end

app/models/job.rb
class Job < ActiveRecord::Base
  has_many :users
  has_many :institutions

  validates :name, presence: true
  validates :institution_id, presence: true
  validates :user_id, presence: true
  validate :check_if_user_has_job_with_same_name
  has_attached_file :avatar, :styles => { :medium => "300x300>", :thumb => "100x100>" }, :default_url => ":style/user.png"
  validates_attachment_content_type :avatar, :content_type => /\Aimage\/.*\Z/

  def check_if_user_has_job_with_same_name
    if self.user_id
      user = User.find(self.user_id)
      user.jobs.each do |job|
        errors.add(:name, "User has a job with the same name already") if job.name == self.name
      end
    end
  end

end

app/models/project.rb
class Project < ActiveRecord::Base
  has_many :users
  has_many :institutions

  validates :name, presence: true
  validates :institution_id, presence: true
  validates :user_id, presence: true
  validate :check_if_user_has_job_with_same_name
  has_attached_file :avatar, :styles => { :medium => "300x300>", :thumb => "100x100>" }, :default_url => ":style/user.png"
  validates_attachment_content_type :avatar, :content_type => /\Aimage\/.*\Z/

  def check_if_user_has_job_with_same_name
    if self.user_id
      user = User.find(self.user_id)
      user.projects.each do |project|
        errors.add(:name, "User has a project with the same name already") if project.name == self.name
      end
    end
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :jobs
  has_many :projects
  has_many :articles
  has_many :blogs
  has_attached_file :avatar, :styles => { :medium => "300x300>", :thumb => "100x100>" }, :default_url => ":style/user.png"
  validates_attachment_content_type :avatar, :content_type => /\Aimage\/.*\Z/
end

app/controllers/environments_controller.rb
class EnvironmentsController < PrivateController
  before_action :set_environment, only: [:show, :edit, :update, :destroy]
  before_filter :is_logged_in?, only: [:edit, :update, :destroy, :new, :create]

  # GET /environments
  # GET /environments.json
  def index
    @environments = Environment.all
  end

  # GET /environments/1
  # GET /environments/1.json
  def show
  end

  # GET /environments/new
  def new
    @environment = Environment.new
  end

  # GET /environments/1/edit
  def edit
  end

  # POST /environments
  # POST /environments.json
  def create
    @environment = Environment.new(environment_params)

    respond_to do |format|
      save_object @environment, format
    end
  end

  # PATCH/PUT /environments/1
  # PATCH/PUT /environments/1.json
  def update
    respond_to do |format|
      update_params @environment, environment_params, format
    end
  end

  # DELETE /environments/1
  # DELETE /environments/1.json
  def destroy
    destroy_object @environment
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_environment
      @environment = Environment.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def environment_params
      params.require(:environment).permit(:name, :can_sign_up)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  skip_before_filter :authenticate_user!, only: [:index, :about]

  def index
  end

  def about
    @user = User.first
    @blogs = @user.blogs
  end
end

app/controllers/jobs_controller.rb
class JobsController < PrivateController
  skip_before_filter :authenticate_user!, only: [:show, :index]
  before_action :set_job, only: [:show, :edit, :update, :destroy]
  before_action :set_institution, only: [:edit, :new, :create, :update]

  # GET /jobs
  # GET /jobs.json
  def index
    @jobs = Job.all
  end

  # GET /jobs/1
  # GET /jobs/1.json
  def show
  end

  # GET /jobs/new
  def new
    @job = Job.new

  end

  # GET /jobs/1/edit
  def edit
  end

  # POST /jobs
  # POST /jobs.json
  def create
    @job = Job.new(job_params)
    add_inst_and_user @job, job_params

    respond_to do |format|
      save_object @job, format
    end
  end

  # PATCH/PUT /jobs/1
  # PATCH/PUT /jobs/1.json
  def update
    respond_to do |format|
      update_params @job, job_params, format
    end
  end

  # DELETE /jobs/1
  # DELETE /jobs/1.json
  def destroy
    destroy_object @job
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_job
      @job = Job.find(params[:id])
    end

    def set_institution
      @institutions = []
      Institution.all.each {|inst| @institutions << [inst.acronym, inst.id]}
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def job_params
      params.require(:job).permit(:name, :institution_id, :responsabilities, :position, :start_date, :current, :end_date, :link, :avatar)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/blogs_helper.rb
module BlogsHelper
end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/helpers/environments_helper.rb
module EnvironmentsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/institutions_helper.rb
module InstitutionsHelper
end

app/helpers/jobs_helper.rb
module JobsHelper
end

app/helpers/private_helper.rb
module PrivateHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/search_helper.rb
module SearchHelper
end

app/views/environments/_form.html.erb
<%= form_for(@environment) do |f| %>
  <% if @environment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@environment.errors.count, "error") %> prohibited this environment from being saved:</h2>

      <ul>
      <% @environment.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label t(:name) %>
    <%= f.text_field :name,autofocus: true, class: "form-control"  %>
  </div>

  <div class="checkbox form-group">
    <%= f.label :can_sign_up do %>
      <%= f.check_box :can_sign_up  %>
      <%=t "Can users sign up?" %>
    <% end %>
  </div>

  <div class="actions">
    <%= f.submit class: "btn btn-default"  %>
  </div>
<% end %>

<br />

app/views/environments/edit.html.erb
<div class="col-xs-12 col-sm-6 col-md-2 hidden-sm ">
</div>

<div class="col-xs-12 col-sm-12 col-md-6">
  <div class="text-center">
    <h1><%=t "Editing Environment" %></h1>
  </div>

  <%= render 'form' %>

  <%= link_to t('Show'), @environment, class: "btn btn-default" %>
  <%= link_to t('Back'), environments_path, class: "btn btn-default" %>
</div>

app/views/environments/index.html.erb
<h2 class="text-center"> <%=t "Environments" %></h2>

<div class="table-responsive">
  <table class="table table-striped table-hover">
    <thead>
      <tr>
        <th colspan="1" class="text-center"><%=t "Name" %></th>
        <th colspan="3" class="text-center"><%=t "Actions" %></th>
      </tr>
    </thead>

    <tbody>
      <% @environments.each do |environment| %>
      <tr>
        <td class="text-center" width="75%"><%= "#{environment.name}" %></td>
        <td>
          <%= link_to environment, title: "Go to this environment", class: "btn btn-default" do %>
            <i class="glyphicon glyphicon-home", aria-hidden="true"></i>
          <% end %>
        </td>
        <td>
          <%= link_to edit_environment_path(environment), title: "Edit this environment", class: "btn btn-default" do %>
            <i class="glyphicon glyphicon-pencil" aria-hidden="true"></i>
          <% end %>
        </td>
        <td>
          <% can_delete = @environments.count > 1 ? true : false %>
          <% if can_delete %>
            <%= link_to environment, title: "Destroy this environment", method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-default" do %>
              <i class="glyphicon glyphicon-trash" aria-hidden="true"></i>
            <% end %>
          <% else %>
            <%= link_to "#", title: "You can't delete your only environemtn", class: "btn btn-default btn-disabled", disabled: true do %>
              <i class="glyphicon glyphicon-trash" aria-hidden="true"></i>
            <% end %>
          <% end %>
        </td>
      </tr>
      <% end %>
    </tbody>
  </table>
</div>

<br>

<%= link_to t('New environment'), new_blog_path, class: "btn btn-default" %>

app/views/environments/new.html.erb
<div class="col-xs-12 col-sm-6 col-md-2 hidden-sm ">
</div>

<div class="col-xs-12 col-sm-12 col-md-6">
  <div class="text-center">
    <h1><%=t "New Environment" %></h1>
  </div>

  <%= render 'form' %>

  <%= link_to t('Back'), environments_path, class: "btn btn-default" %>
</div>

app/views/environments/show.html.erb
<h1><%= @environment.name %> </h1>

<br />

<h4><%= t("Can users sign up?") + " " + (@environment.can_sign_up ? t("Yes") : t("No")) %></h4>

<br />

<%= link_to t('Edit'), edit_environment_path(@environment), class: "btn btn-default" %>
<%= link_to t('Back'), environments_path, class: "btn btn-default" %>